# entries_added_to_dicom_dict.py
"""DICOM dictionary of entries added from Mayo's Matlab dict auto-generated by 
DICOM-CT-PD-dict_to_pydicom.py"""
from __future__ import absolute_import

DicomDictionary = {
