
#ifndef LIBWAVELETSMEX_EXPORT_H
#define LIBWAVELETSMEX_EXPORT_H

#ifdef LIBWAVELETSMEX_STATIC_DEFINE
#  define LIBWAVELETSMEX_EXPORT
#  define LIBWAVELETSMEX_NO_EXPORT
#else
#  ifndef LIBWAVELETSMEX_EXPORT
#    ifdef LIBWAVELETSMEX_EXPORTS
        /* We are building this library */
#      define LIBWAVELETSMEX_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define LIBWAVELETSMEX_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef LIBWAVELETSMEX_NO_EXPORT
#    define LIBWAVELETSMEX_NO_EXPORT 
#  endif
#endif

#ifndef LIBWAVELETSMEX_DEPRECATED
#  define LIBWAVELETSMEX_DEPRECATED __declspec(deprecated)
#endif

#ifndef LIBWAVELETSMEX_DEPRECATED_EXPORT
#  define LIBWAVELETSMEX_DEPRECATED_EXPORT LIBWAVELETSMEX_EXPORT LIBWAVELETSMEX_DEPRECATED
#endif

#ifndef LIBWAVELETSMEX_DEPRECATED_NO_EXPORT
#  define LIBWAVELETSMEX_DEPRECATED_NO_EXPORT LIBWAVELETSMEX_NO_EXPORT LIBWAVELETSMEX_DEPRECATED
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define LIBWAVELETSMEX_NO_DEPRECATED
#endif

#endif
